In [1]:
import pandas as pd

In [2]:
data_df = pd.read_json("static/resources/HH_Jobs_Income_MedHHPrice_PctChange_91_16.json")

In [3]:
# data_df = data_df.round(2)

In [4]:
# data_df
# data_df.set_index("County", inplace=True)
data_df

           County  Households    Income      Jobs  Median Home Price  Year
0          Solano    0.015076  0.054589  0.017005          -0.009175  1992
1          Solano    0.012224  0.011000 -0.000101          -0.028409  1993
2          Solano    0.012765  0.035535  0.058372          -0.021894  1994
3          Solano    0.013260 -0.039308 -0.025286          -0.034759  1995
4          Solano    0.010720 -0.001357 -0.002340          -0.043673  1996
5          Solano    0.009277  0.053012  0.018534           0.008063  1997
6          Solano    0.014009  0.037951  0.041376           0.077152  1998
7          Solano    0.011385  0.039086  0.042621           0.075609  1999
8          Solano    0.015679  0.080156  0.044969           0.221427  2000
9          Solano    0.011522  0.060436  0.035138           0.219670  2001
10         Solano    0.013890  0.015196  0.017150           0.144338  2002
11         Solano    0.013677  0.034201  0.021452           0.151093  2003
12         Solano    0.009764  0.055448  0.001276           0.218256  2004
13         Solano    0.013626  0.035374  0.022891           0.215621  2005
14         Solano    0.014312  0.046681  0.012532           0.029026  2006
15         Solano    0.003135  0.067296 -0.020817          -0.095788  2007
16         Solano    0.004385  0.054318 -0.013718          -0.357334  2008
17         Solano   -0.001318  0.044693 -0.037546          -0.259390  2009
18         Solano   -0.001547 -0.021444  0.004310           0.032576  2010
19         Solano    0.015971  0.029909 -0.021809          -0.096250  2011
20         Solano    0.006296  0.033154  0.016904           0.040865  2012
21         Solano    0.004394  0.024697  0.028750           0.365900  2013
22         Solano    0.005316  0.026599  0.017783           0.178931  2014
23         Solano    0.005605  0.032011  0.029919           0.088109  2015
24         Solano    0.009983  0.023235  0.036738           0.103152  2016
25         Sonoma    0.018955  0.039882 -0.003617           0.054896  1992
26         Sonoma    0.017631  0.011539  0.022250          -0.015888  1993
27         Sonoma    0.011533  0.021190  0.004500          -0.011087  1994
28         Sonoma    0.014768  0.041978  0.024371           0.008318  1995
29         Sonoma    0.011000  0.027163  0.059689          -0.039965  1996
..            ...         ...       ...       ...                ...   ...
196  Contra Costa    0.005656  0.016840  0.026725           0.154708  2012
197  Contra Costa    0.004484  0.011855  0.028252           0.374288  2013
198  Contra Costa    0.005371  0.017501  0.020017           0.097087  2014
199  Contra Costa    0.006948  0.030233  0.022344           0.072238  2015
200  Contra Costa    0.008574  0.021868  0.035691           0.076190  2016
201       Alameda    0.002634  0.050475 -0.015230          -0.029101  1992
202       Alameda    0.007146  0.015062  0.002123          -0.026120  1993
203       Alameda    0.008225  0.031184  0.001386          -0.033859  1994
204       Alameda    0.006891  0.033815  0.037219          -0.010142  1995
205       Alameda    0.008830  0.037339  0.026973           0.036608  1996
206       Alameda    0.007940  0.073613  0.017734           0.071047  1997
207       Alameda    0.009109  0.047618  0.031849           0.112522  1998
208       Alameda    0.013277  0.058981  0.032117           0.126300  1999
209       Alameda    0.012667  0.098715  0.036880           0.285788  2000
210       Alameda    0.007529  0.029543 -0.000049           0.074412  2001
211       Alameda    0.003684  0.017596 -0.021792           0.119568  2002
212       Alameda    0.004311  0.032025 -0.005862           0.066914  2003
213       Alameda    0.003743  0.052845 -0.008536           0.216127  2004
214       Alameda    0.004795  0.034045  0.004875           0.139672  2005
215       Alameda    0.004123  0.052077  0.012045           0.009056  2006
216       Alameda    0.003614  0.040576  0.004445           0.016062  2007
217       Alameda    0.005513  0.008197 -0.005179          -0.298276  2008
218       Alameda    0.003620  0.003358 -0.061704          -0.198504  2009
219       Alameda    0.002022  0.039278 -0.016547           0.144292  2010
220       Alameda    0.006754  0.017883  0.007361          -0.087008  2011
221       Alameda    0.005541  0.022306  0.037363           0.088566  2012
222       Alameda    0.006311 -0.001964  0.029254           0.332473  2013
223       Alameda    0.006070  0.034628  0.030323           0.137051  2014
224       Alameda    0.011562  0.046522  0.043604           0.104737  2015
225       Alameda    0.006878  0.025759  0.031007           0.074380  2016

[226 rows x 6 columns]

In [5]:
data_df.dtypes

County                object
Households           float64
Income               float64
Jobs                 float64
Median Home Price    float64
Year                   int64
dtype: object

In [6]:
data_df.Year = data_df.Year.astype(float)

In [7]:
data_df.dtypes

County                object
Households           float64
Income               float64
Jobs                 float64
Median Home Price    float64
Year                 float64
dtype: object

In [8]:
data_df["County"].unique()

array(['Solano', 'Sonoma', 'San Clara', 'San Mateo', 'San Francisco',
       'Marin', 'Contra Costa', 'Alameda'], dtype=object)

In [9]:
len(data_df)

226

In [10]:
count = 0
child_dict = {}
parent_dict = {}
final_plotly_list = []

current_county = data_df.County[count]
child_dict["year"] = [round(data_df.Year[count],1)]
child_dict["Households"] = [round(data_df.Households[count],2)]
child_dict["Income"] = [round(data_df.Income[count],2)]
child_dict["Jobs"] = [round(data_df.Jobs[count],2)]
child_dict["Median Home Price"] = [round(data_df["Median Home Price"][count],2)]

for x in range(len(data_df.County)):
    

#     print(data.County[x])
    if data_df.County[x] == current_county:
        print(data_df.County[x])
#         county_list.append(data.County[x])
        child_dict["year"].append(round(data_df.Year[x],1))
        child_dict["Households"].append(round(data_df.Households[x],2))
        child_dict["Income"].append(round(data_df.Income[x],2))
        child_dict["Jobs"].append(round(data_df.Jobs[x],2))
        child_dict["Median Home Price"].append(round(data_df["Median Home Price"][x],2))
        
    else:
        parent_dict[data_df.County[x]] = child_dict
        count += 1
# child_dict = {}

        
# print(parent_dict)
        
final_plotly_list.append(parent_dict)
print(final_plotly_list)

Solano
Solano
Solano
Solano
Solano
Solano
Solano
Solano
Solano
Solano
Solano
Solano
Solano
Solano
Solano
Solano
Solano
Solano
Solano
Solano
Solano
Solano
Solano
Solano
Solano
[{'Sonoma': {'year': [1992.0, 1992.0, 1993.0, 1994.0, 1995.0, 1996.0, 1997.0, 1998.0, 1999.0, 2000.0, 2001.0, 2002.0, 2003.0, 2004.0, 2005.0, 2006.0, 2007.0, 2008.0, 2009.0, 2010.0, 2011.0, 2012.0, 2013.0, 2014.0, 2015.0, 2016.0], 'Households': [0.02, 0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0, 0.0, -0.0, -0.0, 0.02, 0.01, 0.0, 0.01, 0.01, 0.01], 'Income': [0.050000000000000003, 0.050000000000000003, 0.01, 0.040000000000000001, -0.040000000000000001, -0.0, 0.050000000000000003, 0.040000000000000001, 0.040000000000000001, 0.080000000000000002, 0.059999999999999998, 0.02, 0.029999999999999999, 0.059999999999999998, 0.040000000000000001, 0.050000000000000003, 0.070000000000000007, 0.050000000000000003, 0.040000000000000001, -0.02, 0.029999999999999999, 0.029999999999999999, 0.02, 0.029999999999999999, 0.029999999999999999, 0.02], 'Jobs': [0.02, 0.02, -0.0, 0.059999999999999998, -0.029999999999999999, -0.0, 0.02, 0.040000000000000001, 0.040000000000000001, 0.040000000000000001, 0.040000000000000001, 0.02, 0.02, 0.0, 0.02, 0.01, -0.02, -0.01, -0.040000000000000001, 0.0, -0.02, 0.02, 0.029999999999999999, 0.02, 0.029999999999999999, 0.040000000000000001], 'Median Home Price': [-0.01, -0.01, -0.029999999999999999, -0.02, -0.029999999999999999, -0.040000000000000001, 0.01, 0.080000000000000002, 0.080000000000000002, 0.22, 0.22, 0.14000000000000001, 0.14999999999999999, 0.22, 0.22, 0.029999999999999999, -0.10000000000000001, -0.35999999999999999, -0.26000000000000001, 0.029999999999999999, -0.10000000000000001, 0.040000000000000001, 0.37, 0.17999999999999999, 0.089999999999999997, 0.10000000000000001]}, 'San Clara': {'year': [1992.0, 1992.0, 1993.0, 1994.0, 1995.0, 1996.0, 1997.0, 1998.0, 1999.0, 2000.0, 2001.0, 2002.0, 2003.0, 2004.0, 2005.0, 2006.0, 2007.0, 2008.0, 2009.0, 2010.0, 2011.0, 2012.0, 2013.0, 2014.0, 2015.0, 2016.0], 'Households': [0.02, 0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0, 0.0, -0.0, -0.0, 0.02, 0.01, 0.0, 0.01, 0.01, 0.01], 'Income': [0.050000000000000003, 0.050000000000000003, 0.01, 0.040000000000000001, -0.040000000000000001, -0.0, 0.050000000000000003, 0.040000000000000001, 0.040000000000000001, 0.080000000000000002, 0.059999999999999998, 0.02, 0.029999999999999999, 0.059999999999999998, 0.040000000000000001, 0.050000000000000003, 0.070000000000000007, 0.050000000000000003, 0.040000000000000001, -0.02, 0.029999999999999999, 0.029999999999999999, 0.02, 0.029999999999999999, 0.029999999999999999, 0.02], 'Jobs': [0.02, 0.02, -0.0, 0.059999999999999998, -0.029999999999999999, -0.0, 0.02, 0.040000000000000001, 0.040000000000000001, 0.040000000000000001, 0.040000000000000001, 0.02, 0.02, 0.0, 0.02, 0.01, -0.02, -0.01, -0.040000000000000001, 0.0, -0.02, 0.02, 0.029999999999999999, 0.02, 0.029999999999999999, 0.040000000000000001], 'Median Home Price': [-0.01, -0.01, -0.029999999999999999, -0.02, -0.029999999999999999, -0.040000000000000001, 0.01, 0.080000000000000002, 0.080000000000000002, 0.22, 0.22, 0.14000000000000001, 0.14999999999999999, 0.22, 0.22, 0.029999999999999999, -0.10000000000000001, -0.35999999999999999, -0.26000000000000001, 0.029999999999999999, -0.10000000000000001, 0.040000000000000001, 0.37, 0.17999999999999999, 0.089999999999999997, 0.10000000000000001]}, 'San Mateo': {'year': [1992.0, 1992.0, 1993.0, 1994.0, 1995.0, 1996.0, 1997.0, 1998.0, 1999.0, 2000.0, 2001.0, 2002.0, 2003.0, 2004.0, 2005.0, 2006.0, 2007.0, 2008.0, 2009.0, 2010.0, 2011.0, 2012.0, 2013.0, 2014.0, 2015.0, 2016.0], 'Households': [0.02, 0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0, 0.0, -0.0, -0.0, 0.02, 0.01, 0.0, 0.01, 0.01, 0.01], 'Income': [0.050000000000000003, 0.050000000000000003, 0.01, 0.040000000000000001, -0.040000000000000001, -0.0, 0.050000000000000003, 0.040000000000000001, 0.040000000000000001, 0.080000000000000002, 0.059999999999999998, 0.02, 0.029999999999999999, 0.059999999999999998, 0.040000000000000001, 0.050000000000000003, 0.070000000000000007, 0.050000000000000003, 0.040000000000000001, -0.02, 0.029999999999999999, 0.029999999999999999, 0.02, 0.029999999999999999, 0.029999999999999999, 0.02], 'Jobs': [0.02, 0.02, -0.0, 0.059999999999999998, -0.029999999999999999, -0.0, 0.02, 0.040000000000000001, 0.040000000000000001, 0.040000000000000001, 0.040000000000000001, 0.02, 0.02, 0.0, 0.02, 0.01, -0.02, -0.01, -0.040000000000000001, 0.0, -0.02, 0.02, 0.029999999999999999, 0.02, 0.029999999999999999, 0.040000000000000001], 'Median Home Price': [-0.01, -0.01, -0.029999999999999999, -0.02, -0.029999999999999999, -0.040000000000000001, 0.01, 0.080000000000000002, 0.080000000000000002, 0.22, 0.22, 0.14000000000000001, 0.14999999999999999, 0.22, 0.22, 0.029999999999999999, -0.10000000000000001, -0.35999999999999999, -0.26000000000000001, 0.029999999999999999, -0.10000000000000001, 0.040000000000000001, 0.37, 0.17999999999999999, 0.089999999999999997, 0.10000000000000001]}, 'San Francisco': {'year': [1992.0, 1992.0, 1993.0, 1994.0, 1995.0, 1996.0, 1997.0, 1998.0, 1999.0, 2000.0, 2001.0, 2002.0, 2003.0, 2004.0, 2005.0, 2006.0, 2007.0, 2008.0, 2009.0, 2010.0, 2011.0, 2012.0, 2013.0, 2014.0, 2015.0, 2016.0], 'Households': [0.02, 0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0, 0.0, -0.0, -0.0, 0.02, 0.01, 0.0, 0.01, 0.01, 0.01], 'Income': [0.050000000000000003, 0.050000000000000003, 0.01, 0.040000000000000001, -0.040000000000000001, -0.0, 0.050000000000000003, 0.040000000000000001, 0.040000000000000001, 0.080000000000000002, 0.059999999999999998, 0.02, 0.029999999999999999, 0.059999999999999998, 0.040000000000000001, 0.050000000000000003, 0.070000000000000007, 0.050000000000000003, 0.040000000000000001, -0.02, 0.029999999999999999, 0.029999999999999999, 0.02, 0.029999999999999999, 0.029999999999999999, 0.02], 'Jobs': [0.02, 0.02, -0.0, 0.059999999999999998, -0.029999999999999999, -0.0, 0.02, 0.040000000000000001, 0.040000000000000001, 0.040000000000000001, 0.040000000000000001, 0.02, 0.02, 0.0, 0.02, 0.01, -0.02, -0.01, -0.040000000000000001, 0.0, -0.02, 0.02, 0.029999999999999999, 0.02, 0.029999999999999999, 0.040000000000000001], 'Median Home Price': [-0.01, -0.01, -0.029999999999999999, -0.02, -0.029999999999999999, -0.040000000000000001, 0.01, 0.080000000000000002, 0.080000000000000002, 0.22, 0.22, 0.14000000000000001, 0.14999999999999999, 0.22, 0.22, 0.029999999999999999, -0.10000000000000001, -0.35999999999999999, -0.26000000000000001, 0.029999999999999999, -0.10000000000000001, 0.040000000000000001, 0.37, 0.17999999999999999, 0.089999999999999997, 0.10000000000000001]}, 'Marin': {'year': [1992.0, 1992.0, 1993.0, 1994.0, 1995.0, 1996.0, 1997.0, 1998.0, 1999.0, 2000.0, 2001.0, 2002.0, 2003.0, 2004.0, 2005.0, 2006.0, 2007.0, 2008.0, 2009.0, 2010.0, 2011.0, 2012.0, 2013.0, 2014.0, 2015.0, 2016.0], 'Households': [0.02, 0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0, 0.0, -0.0, -0.0, 0.02, 0.01, 0.0, 0.01, 0.01, 0.01], 'Income': [0.050000000000000003, 0.050000000000000003, 0.01, 0.040000000000000001, -0.040000000000000001, -0.0, 0.050000000000000003, 0.040000000000000001, 0.040000000000000001, 0.080000000000000002, 0.059999999999999998, 0.02, 0.029999999999999999, 0.059999999999999998, 0.040000000000000001, 0.050000000000000003, 0.070000000000000007, 0.050000000000000003, 0.040000000000000001, -0.02, 0.029999999999999999, 0.029999999999999999, 0.02, 0.029999999999999999, 0.029999999999999999, 0.02], 'Jobs': [0.02, 0.02, -0.0, 0.059999999999999998, -0.029999999999999999, -0.0, 0.02, 0.040000000000000001, 0.040000000000000001, 0.040000000000000001, 0.040000000000000001, 0.02, 0.02, 0.0, 0.02, 0.01, -0.02, -0.01, -0.040000000000000001, 0.0, -0.02, 0.02, 0.029999999999999999, 0.02, 0.029999999999999999, 0.040000000000000001], 'Median Home Price': [-0.01, -0.01, -0.029999999999999999, -0.02, -0.029999999999999999, -0.040000000000000001, 0.01, 0.080000000000000002, 0.080000000000000002, 0.22, 0.22, 0.14000000000000001, 0.14999999999999999, 0.22, 0.22, 0.029999999999999999, -0.10000000000000001, -0.35999999999999999, -0.26000000000000001, 0.029999999999999999, -0.10000000000000001, 0.040000000000000001, 0.37, 0.17999999999999999, 0.089999999999999997, 0.10000000000000001]}, 'Contra Costa': {'year': [1992.0, 1992.0, 1993.0, 1994.0, 1995.0, 1996.0, 1997.0, 1998.0, 1999.0, 2000.0, 2001.0, 2002.0, 2003.0, 2004.0, 2005.0, 2006.0, 2007.0, 2008.0, 2009.0, 2010.0, 2011.0, 2012.0, 2013.0, 2014.0, 2015.0, 2016.0], 'Households': [0.02, 0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0, 0.0, -0.0, -0.0, 0.02, 0.01, 0.0, 0.01, 0.01, 0.01], 'Income': [0.050000000000000003, 0.050000000000000003, 0.01, 0.040000000000000001, -0.040000000000000001, -0.0, 0.050000000000000003, 0.040000000000000001, 0.040000000000000001, 0.080000000000000002, 0.059999999999999998, 0.02, 0.029999999999999999, 0.059999999999999998, 0.040000000000000001, 0.050000000000000003, 0.070000000000000007, 0.050000000000000003, 0.040000000000000001, -0.02, 0.029999999999999999, 0.029999999999999999, 0.02, 0.029999999999999999, 0.029999999999999999, 0.02], 'Jobs': [0.02, 0.02, -0.0, 0.059999999999999998, -0.029999999999999999, -0.0, 0.02, 0.040000000000000001, 0.040000000000000001, 0.040000000000000001, 0.040000000000000001, 0.02, 0.02, 0.0, 0.02, 0.01, -0.02, -0.01, -0.040000000000000001, 0.0, -0.02, 0.02, 0.029999999999999999, 0.02, 0.029999999999999999, 0.040000000000000001], 'Median Home Price': [-0.01, -0.01, -0.029999999999999999, -0.02, -0.029999999999999999, -0.040000000000000001, 0.01, 0.080000000000000002, 0.080000000000000002, 0.22, 0.22, 0.14000000000000001, 0.14999999999999999, 0.22, 0.22, 0.029999999999999999, -0.10000000000000001, -0.35999999999999999, -0.26000000000000001, 0.029999999999999999, -0.10000000000000001, 0.040000000000000001, 0.37, 0.17999999999999999, 0.089999999999999997, 0.10000000000000001]}, 'Alameda': {'year': [1992.0, 1992.0, 1993.0, 1994.0, 1995.0, 1996.0, 1997.0, 1998.0, 1999.0, 2000.0, 2001.0, 2002.0, 2003.0, 2004.0, 2005.0, 2006.0, 2007.0, 2008.0, 2009.0, 2010.0, 2011.0, 2012.0, 2013.0, 2014.0, 2015.0, 2016.0], 'Households': [0.02, 0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0, 0.0, -0.0, -0.0, 0.02, 0.01, 0.0, 0.01, 0.01, 0.01], 'Income': [0.050000000000000003, 0.050000000000000003, 0.01, 0.040000000000000001, -0.040000000000000001, -0.0, 0.050000000000000003, 0.040000000000000001, 0.040000000000000001, 0.080000000000000002, 0.059999999999999998, 0.02, 0.029999999999999999, 0.059999999999999998, 0.040000000000000001, 0.050000000000000003, 0.070000000000000007, 0.050000000000000003, 0.040000000000000001, -0.02, 0.029999999999999999, 0.029999999999999999, 0.02, 0.029999999999999999, 0.029999999999999999, 0.02], 'Jobs': [0.02, 0.02, -0.0, 0.059999999999999998, -0.029999999999999999, -0.0, 0.02, 0.040000000000000001, 0.040000000000000001, 0.040000000000000001, 0.040000000000000001, 0.02, 0.02, 0.0, 0.02, 0.01, -0.02, -0.01, -0.040000000000000001, 0.0, -0.02, 0.02, 0.029999999999999999, 0.02, 0.029999999999999999, 0.040000000000000001], 'Median Home Price': [-0.01, -0.01, -0.029999999999999999, -0.02, -0.029999999999999999, -0.040000000000000001, 0.01, 0.080000000000000002, 0.080000000000000002, 0.22, 0.22, 0.14000000000000001, 0.14999999999999999, 0.22, 0.22, 0.029999999999999999, -0.10000000000000001, -0.35999999999999999, -0.26000000000000001, 0.029999999999999999, -0.10000000000000001, 0.040000000000000001, 0.37, 0.17999999999999999, 0.089999999999999997, 0.10000000000000001]}}]

In [30]:
# data_df.to_json(orient="records")