In [4]:
import pandas as pd
import numpy as np

In [5]:
data_df = pd.read_csv("static/resources/MinimumQualifyingIncomePastANDFuture_5YrIntervals.csv")

In [7]:
data_df.head()

,Year,County,Avg.Median Home price,Interest_Rate,QualifyingIncome,AvgAnnualIncome
0,1995,Alameda,207880,7.85,57684,33263
1,2000,Alameda,371850,7.96,104100,45155
2,2005,Alameda,661420,5.90,155940,53152
3,2010,Alameda,436433,4.91,94272,61175
4,2015,Alameda,726000,4.03,144720,68791

In [8]:
data_df.dtypes

Year                       int64
County                    object
Avg.Median Home price      int64
Interest_Rate            float64
QualifyingIncome           int64
AvgAnnualIncome            int64
dtype: object

In [10]:
data_df.Year = data_df.Year.astype(float)
data_df["Avg.Median Home price"] = data_df["Avg.Median Home price"].astype(float)
data_df["QualifyingIncome"] = data_df["QualifyingIncome"].astype(float)
data_df["AvgAnnualIncome"] = data_df["AvgAnnualIncome"].astype(float)

In [11]:
data_df.dtypes

Year                     float64
County                    object
Avg.Median Home price    float64
Interest_Rate            float64
QualifyingIncome         float64
AvgAnnualIncome          float64
dtype: object

In [12]:
data_df["County"].unique()

array(['Alameda', 'Bay Area', 'Contra Costa', 'Marin', 'Napa',
       'San Francisco', 'San Mateo', 'Santa Clara', 'Solano', 'Sonoma'], dtype=object)

In [13]:
len(data_df)

101

In [14]:
counties = ['Bay Area', 'Solano', 'Sonoma', 'Santa Clara', 'San Mateo',
       'San Francisco', 'Napa', 'Marin', 'Contra Costa', 'Alameda']
final_dict = {}
for county in counties:
    temp_dict = {}
#     print(county)
    current_df = data_df.loc[data_df["County"] == county]
    year_list = current_df['Year'].tolist()       
    avg_income_list = current_df['AvgAnnualIncome'].tolist() 
    qualifying_income_list = current_df['QualifyingIncome'].tolist() 
    homeprice_list = current_df['Avg.Median Home price'].tolist()
    temp_dict["year"] = year_list
    temp_dict["avgAnnualIncome"] = avg_income_list
    temp_dict["qualifyingIncome"] = qualifying_income_list
    temp_dict["medianHomePrice"] = homeprice_list
    final_dict[county] = temp_dict
    print(temp_dict)
# final_dict

{'year': [1995.0, 2000.0, 2005.0, 2010.0, 2015.0, 2020.0, 2025.0, 2030.0, 2035.0, 2040.0], 'avgAnnualIncome': [32788.0, 48066.0, 53537.0, 61177.0, 73803.0, 83971.0, 93573.0, 103176.0, 112779.0, 122382.0], 'qualifyingIncome': [66408.0, 121440.0, 161652.0, 97020.0, 145608.0, 147467.0, 162664.0, 177895.0, 193296.0, 208603.0], 'medianHomePrice': [239315.0, 433890.0, 685463.0, 449088.0, 730536.0, 894098.0, 986243.0, 1078589.0, 1171963.0, 1264768.0]}
{'year': [1995.0, 2000.0, 2005.0, 2010.0, 2015.0, 2020.0, 2025.0, 2030.0, 2035.0, 2040.0], 'avgAnnualIncome': [25784.0, 31587.0, 38431.0, 46273.0, 53453.0, 60414.0, 66892.0, 73370.0, 79848.0, 86326.0], 'qualifyingIncome': [39564.0, 54468.0, 109176.0, 45744.0, 69576.0, 63961.0, 61394.0, 61460.0, 61547.0, 56350.0], 'medianHomePrice': [142650.0, 194610.0, 463030.0, 211740.0, 349000.0, 387801.0, 372237.0, 372633.0, 373161.0, 341656.0]}
{'year': [1995.0, 2000.0, 2000.0, 2005.0, 2010.0, 2015.0, 2020.0, 2025.0, 2030.0, 2035.0, 2040.0], 'avgAnnualIncome': [26212.0, 35803.0, 35803.0, 40017.0, 44192.0, 49398.0, 55316.0, 60813.0, 66309.0, 71806.0, 77302.0], 'qualifyingIncome': [54144.0, 89076.0, 89076.0, 148044.0, 78468.0, 105612.0, 133461.0, 138441.0, 142217.0, 157020.0, 174618.0], 'medianHomePrice': [195170.0, 318190.0, 318190.0, 627910.0, 363120.0, 529750.0, 809178.0, 839376.0, 862268.0, 952018.0, 1058716.0]}
{'year': [1995.0, 2000.0, 2005.0, 2010.0, 2015.0, 2020.0, 2025.0, 2030.0, 2035.0, 2040.0], 'avgAnnualIncome': [42892.0, 76354.0, 72693.0, 89401.0, 113390.0, 135872.0, 151986.0, 168099.0, 184212.0, 200326.0], 'qualifyingIncome': [70824.0, 146664.0, 173328.0, 128532.0, 189552.0, 201953.0, 247183.0, 291427.0, 355046.0, 409145.0], 'medianHomePrice': [255260.0, 524000.0, 735000.0, 595000.0, 951000.0, 1224452.0, 1498682.0, 1766938.0, 2152661.0, 2480666.0]}
{'year': [1995.0, 2000.0, 2005.0, 2010.0, 2015.0, 2020.0, 2025.0, 2030.0, 2035.0, 2040.0], 'avgAnnualIncome': [37176.0, 67084.0, 66573.0, 74254.0, 102776.0, 125414.0, 140787.0, 156160.0, 171533.0, 186905.0], 'qualifyingIncome': [88224.0, 171408.0, 212988.0, 155664.0, 249144.0, 299773.0, 336957.0, 403306.0, 445289.0, 503297.0], 'medianHomePrice': [317890.0, 612380.0, 903230.0, 720500.0, 1250000.0, 1817541.0, 2042989.0, 2445263.0, 2699809.0, 3051516.0]}
{'year': [1995.0, 2000.0, 2005.0, 2010.0, 2015.0, 2020.0, 2025.0, 2030.0, 2035.0, 2040.0], 'avgAnnualIncome': [39708.0, 57723.0, 66590.0, 76361.0, 97067.0, 113663.0, 126975.0, 140288.0, 153600.0, 166913.0], 'qualifyingIncome': [74556.0, 150060.0, 205392.0, 161772.0, 249144.0, 184434.0, 208952.0, 238465.0, 263554.0, 272517.0], 'medianHomePrice': [268635.0, 536058.0, 871042.0, 748855.0, 1250000.0, 1118235.0, 1266885.0, 1445826.0, 1597943.0, 1652284.0]}
{'year': [1995.0, 2000.0, 2005.0, 2010.0, 2015.0, 2020.0, 2025.0, 2030.0, 2035.0, 2040.0], 'avgAnnualIncome': [25500.0, 33104.0, 40180.0, 45250.0, 50650.0, 57390.0, 63531.0, 69673.0, 75815.0, 81957.0], 'qualifyingIncome': [50928.0, 84384.0, 154608.0, 78312.0, 119604.0, 71358.0, 74238.0, 77499.0, 86565.0, 76326.0], 'medianHomePrice': [183550.0, 301490.0, 655720.0, 362460.0, 600000.0, 432647.0, 450107.0, 469881.0, 524849.0, 462767.0]}
{'year': [1995.0, 2000.0, 2005.0, 2010.0, 2015.0, 2020.0, 2025.0, 2030.0, 2035.0, 2040.0], 'avgAnnualIncome': [31552.0, 42867.0, 52678.0, 56134.0, 64906.0, 71624.0, 77060.0, 82496.0, 87932.0, 93368.0], 'qualifyingIncome': [95616.0, 180072.0, 230328.0, 175176.0, 219240.0, 237307.0, 255434.0, 273269.0, 288683.0, 302997.0], 'medianHomePrice': [344600.0, 643250.0, 976720.0, 810880.0, 1100000.0, 1438804.0, 1548712.0, 1656842.0, 1750302.0, 1837088.0]}
{'year': [1995.0, 2000.0, 2005.0, 2010.0, 2015.0, 2020.0, 2025.0, 2030.0, 2035.0, 2040.0], 'avgAnnualIncome': [33003.0, 42914.0, 51515.0, 57552.0, 63792.0, 72576.0, 80117.0, 87659.0, 95200.0, 102741.0], 'qualifyingIncome': [56916.0, 84480.0, 138744.0, 64032.0, 104628.0, 166052.0, 172172.0, 183266.0, 191128.0, 214200.0], 'medianHomePrice': [205093.0, 301784.0, 588389.0, 296380.0, 525000.0, 1006783.0, 1043886.0, 1111152.0, 1158817.0, 1298705.0]}
{'year': [1995.0, 2000.0, 2005.0, 2010.0, 2015.0, 2020.0, 2025.0, 2030.0, 2035.0, 2040.0], 'avgAnnualIncome': [33263.0, 45155.0, 53152.0, 61175.0, 68791.0, 77887.0, 86448.0, 95009.0, 103570.0, 112132.0], 'qualifyingIncome': [57684.0, 104100.0, 155940.0, 94272.0, 144720.0, 98594.0, 98480.0, 82058.0, 65837.0, 19473.0], 'medianHomePrice': [207880.0, 371850.0, 661420.0, 436433.0, 726000.0, 597782.0, 597089.0, 497524.0, 399172.0, 118068.0]}

In [15]:
final_dict

{'Alameda': {'avgAnnualIncome': [33263.0,
   45155.0,
   53152.0,
   61175.0,
   68791.0,
   77887.0,
   86448.0,
   95009.0,
   103570.0,
   112132.0],
  'medianHomePrice': [207880.0,
   371850.0,
   661420.0,
   436433.0,
   726000.0,
   597782.0,
   597089.0,
   497524.0,
   399172.0,
   118068.0],
  'qualifyingIncome': [57684.0,
   104100.0,
   155940.0,
   94272.0,
   144720.0,
   98594.0,
   98480.0,
   82058.0,
   65837.0,
   19473.0],
  'year': [1995.0,
   2000.0,
   2005.0,
   2010.0,
   2015.0,
   2020.0,
   2025.0,
   2030.0,
   2035.0,
   2040.0]},
 'Bay Area': {'avgAnnualIncome': [32788.0,
   48066.0,
   53537.0,
   61177.0,
   73803.0,
   83971.0,
   93573.0,
   103176.0,
   112779.0,
   122382.0],
  'medianHomePrice': [239315.0,
   433890.0,
   685463.0,
   449088.0,
   730536.0,
   894098.0,
   986243.0,
   1078589.0,
   1171963.0,
   1264768.0],
  'qualifyingIncome': [66408.0,
   121440.0,
   161652.0,
   97020.0,
   145608.0,
   147467.0,
   162664.0,
   177895.0,
   193296.0,
   208603.0],
  'year': [1995.0,
   2000.0,
   2005.0,
   2010.0,
   2015.0,
   2020.0,
   2025.0,
   2030.0,
   2035.0,
   2040.0]},
 'Contra Costa': {'avgAnnualIncome': [33003.0,
   42914.0,
   51515.0,
   57552.0,
   63792.0,
   72576.0,
   80117.0,
   87659.0,
   95200.0,
   102741.0],
  'medianHomePrice': [205093.0,
   301784.0,
   588389.0,
   296380.0,
   525000.0,
   1006783.0,
   1043886.0,
   1111152.0,
   1158817.0,
   1298705.0],
  'qualifyingIncome': [56916.0,
   84480.0,
   138744.0,
   64032.0,
   104628.0,
   166052.0,
   172172.0,
   183266.0,
   191128.0,
   214200.0],
  'year': [1995.0,
   2000.0,
   2005.0,
   2010.0,
   2015.0,
   2020.0,
   2025.0,
   2030.0,
   2035.0,
   2040.0]},
 'Marin': {'avgAnnualIncome': [31552.0,
   42867.0,
   52678.0,
   56134.0,
   64906.0,
   71624.0,
   77060.0,
   82496.0,
   87932.0,
   93368.0],
  'medianHomePrice': [344600.0,
   643250.0,
   976720.0,
   810880.0,
   1100000.0,
   1438804.0,
   1548712.0,
   1656842.0,
   1750302.0,
   1837088.0],
  'qualifyingIncome': [95616.0,
   180072.0,
   230328.0,
   175176.0,
   219240.0,
   237307.0,
   255434.0,
   273269.0,
   288683.0,
   302997.0],
  'year': [1995.0,
   2000.0,
   2005.0,
   2010.0,
   2015.0,
   2020.0,
   2025.0,
   2030.0,
   2035.0,
   2040.0]},
 'Napa': {'avgAnnualIncome': [25500.0,
   33104.0,
   40180.0,
   45250.0,
   50650.0,
   57390.0,
   63531.0,
   69673.0,
   75815.0,
   81957.0],
  'medianHomePrice': [183550.0,
   301490.0,
   655720.0,
   362460.0,
   600000.0,
   432647.0,
   450107.0,
   469881.0,
   524849.0,
   462767.0],
  'qualifyingIncome': [50928.0,
   84384.0,
   154608.0,
   78312.0,
   119604.0,
   71358.0,
   74238.0,
   77499.0,
   86565.0,
   76326.0],
  'year': [1995.0,
   2000.0,
   2005.0,
   2010.0,
   2015.0,
   2020.0,
   2025.0,
   2030.0,
   2035.0,
   2040.0]},
 'San Francisco': {'avgAnnualIncome': [39708.0,
   57723.0,
   66590.0,
   76361.0,
   97067.0,
   113663.0,
   126975.0,
   140288.0,
   153600.0,
   166913.0],
  'medianHomePrice': [268635.0,
   536058.0,
   871042.0,
   748855.0,
   1250000.0,
   1118235.0,
   1266885.0,
   1445826.0,
   1597943.0,
   1652284.0],
  'qualifyingIncome': [74556.0,
   150060.0,
   205392.0,
   161772.0,
   249144.0,
   184434.0,
   208952.0,
   238465.0,
   263554.0,
   272517.0],
  'year': [1995.0,
   2000.0,
   2005.0,
   2010.0,
   2015.0,
   2020.0,
   2025.0,
   2030.0,
   2035.0,
   2040.0]},
 'San Mateo': {'avgAnnualIncome': [37176.0,
   67084.0,
   66573.0,
   74254.0,
   102776.0,
   125414.0,
   140787.0,
   156160.0,
   171533.0,
   186905.0],
  'medianHomePrice': [317890.0,
   612380.0,
   903230.0,
   720500.0,
   1250000.0,
   1817541.0,
   2042989.0,
   2445263.0,
   2699809.0,
   3051516.0],
  'qualifyingIncome': [88224.0,
   171408.0,
   212988.0,
   155664.0,
   249144.0,
   299773.0,
   336957.0,
   403306.0,
   445289.0,
   503297.0],
  'year': [1995.0,
   2000.0,
   2005.0,
   2010.0,
   2015.0,
   2020.0,
   2025.0,
   2030.0,
   2035.0,
   2040.0]},
 'Santa Clara': {'avgAnnualIncome': [42892.0,
   76354.0,
   72693.0,
   89401.0,
   113390.0,
   135872.0,
   151986.0,
   168099.0,
   184212.0,
   200326.0],
  'medianHomePrice': [255260.0,
   524000.0,
   735000.0,
   595000.0,
   951000.0,
   1224452.0,
   1498682.0,
   1766938.0,
   2152661.0,
   2480666.0],
  'qualifyingIncome': [70824.0,
   146664.0,
   173328.0,
   128532.0,
   189552.0,
   201953.0,
   247183.0,
   291427.0,
   355046.0,
   409145.0],
  'year': [1995.0,
   2000.0,
   2005.0,
   2010.0,
   2015.0,
   2020.0,
   2025.0,
   2030.0,
   2035.0,
   2040.0]},
 'Solano': {'avgAnnualIncome': [25784.0,
   31587.0,
   38431.0,
   46273.0,
   53453.0,
   60414.0,
   66892.0,
   73370.0,
   79848.0,
   86326.0],
  'medianHomePrice': [142650.0,
   194610.0,
   463030.0,
   211740.0,
   349000.0,
   387801.0,
   372237.0,
   372633.0,
   373161.0,
   341656.0],
  'qualifyingIncome': [39564.0,
   54468.0,
   109176.0,
   45744.0,
   69576.0,
   63961.0,
   61394.0,
   61460.0,
   61547.0,
   56350.0],
  'year': [1995.0,
   2000.0,
   2005.0,
   2010.0,
   2015.0,
   2020.0,
   2025.0,
   2030.0,
   2035.0,
   2040.0]},
 'Sonoma': {'avgAnnualIncome': [26212.0,
   35803.0,
   35803.0,
   40017.0,
   44192.0,
   49398.0,
   55316.0,
   60813.0,
   66309.0,
   71806.0,
   77302.0],
  'medianHomePrice': [195170.0,
   318190.0,
   318190.0,
   627910.0,
   363120.0,
   529750.0,
   809178.0,
   839376.0,
   862268.0,
   952018.0,
   1058716.0],
  'qualifyingIncome': [54144.0,
   89076.0,
   89076.0,
   148044.0,
   78468.0,
   105612.0,
   133461.0,
   138441.0,
   142217.0,
   157020.0,
   174618.0],
  'year': [1995.0,
   2000.0,
   2000.0,
   2005.0,
   2010.0,
   2015.0,
   2020.0,
   2025.0,
   2030.0,
   2035.0,
   2040.0]}}

In [16]:
# data_df.to_json(orient="records")